FROM alpine:latest as sources

RUN apk add git

WORKDIR /opt/app
RUN git clone https://github.com/tabixio/tabix.git

WORKDIR /opt/app/tabix
RUN git checkout 18.02.2
RUN rm docker/default

FROM debian:jessie

ENV APP_HOME /usr/src/app
ENV DEFAULT /etc/nginx/sites-enabled/default

RUN apt-get update && apt-get install -y --force-yes nginx-full nginx libssl-dev
RUN apt-get install -y openssl
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR $APP_HOME
COPY --from=sources /opt/app/tabix/docker $APP_HOME
COPY --from=sources /opt/app/tabix/build /var/www/html

RUN rm $DEFAULT
RUN mv default_no_pass $DEFAULT

CMD ./start.sh
